apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-gke
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-gke
  template:
    metadata:
      labels:
        app: flask-gke
    spec:
      containers:
      - name: flask-gke
        image: europe-west1-docker.pkg.dev/$PROJECT_ID/gke-apps/flask-gke:latest
        ports:
        - containerPort: 8080
        env:
        - name: APP_VERSION
          value: "1.0"
